/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xerxes_com_jnipkg_BufferJNI */

#ifndef _Included_xerxes_com_jnipkg_BufferJNI
#define _Included_xerxes_com_jnipkg_BufferJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xerxes_com_jnipkg_BufferJNI
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xerxes_com_jnipkg_BufferJNI_register
  (JNIEnv *, jobject);

/*
 * Class:     xerxes_com_jnipkg_BufferJNI
 * Method:    displayHelloWorld
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xerxes_com_jnipkg_BufferJNI_displayHelloWorld
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xerxes_com_jnipkg_BufferJNI
 * Method:    startRecording
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xerxes_com_jnipkg_BufferJNI_startRecording
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     xerxes_com_jnipkg_BufferJNI
 * Method:    stopRecording
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xerxes_com_jnipkg_BufferJNI_stopRecording
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
