/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeutils_MyRtmp */

#ifndef _Included_nativeutils_MyRtmp
#define _Included_nativeutils_MyRtmp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeutils_MyRtmp
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nativeutils_MyRtmp_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
